import "server-only";

/**
 * Reads `public/sandbox/sound.js` for inlining into a preview document.
 *
 * Fetched rather than read from disk for the same reason the export fetches it:
 * `public/sandbox/vendor/` is generated by `postinstall`, and a deployed
 * function's working directory is not guaranteed to contain it. Cached for the
 * life of the process, because the file only changes on redeploy.
 */
let cached: string | null = null;

export async function readSoundSource(appOrigin: string): Promise<string> {
  if (cached !== null) {
    return cached;
  }

  const response = await fetch(`${appOrigin}/sandbox/sound.js`);

  if (!response.ok) {
    throw new Error(`Could not load sound.js (HTTP ${response.status}).`);
  }

  cached = await response.text();

  return cached;
}
