/**
 * Escaping and module-syntax helpers shared by the export builders.
 *
 * Both exported artifacts embed generated scene source and baked JSON inside
 * `<script>` elements. The HTML parser ends a script element at the first
 * `</script` sequence wherever it appears — inside a string literal, inside a
 * regex, inside minified vendor code — so a scene that merely mentions it would
 * truncate the file and leave a page that silently does nothing.
 *
 * `<!--` is the second terminator-adjacent sequence the parser reacts to: it
 * moves the tokenizer into the script-data-escaped states, where a following
 * `<script>` opens the double-escaped state and the element's real `</script>` is
 * then swallowed as text. Escaping `<!--` keeps the tokenizer from ever leaving
 * the plain script-data state, which is what makes the two rewrites together
 * sufficient.
 */

/** For text nodes and attribute values, e.g. the `<title>` element. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * For content placed inside a `<script>` element.
 *
 * `<\/script` and `<\u0021--` are the spellings the HTML parser does not
 * recognise, and in JavaScript both are the same characters the code started
 * with, so it keeps its meaning. This is applied to the scene source, the baked
 * manifest, and the vendor bundles alike: the source is machine-generated, but
 * "generated by a model" is not a reason to trust that it never contains the
 * sequence.
 *
 * The comment opener is escaped with `\u0021` rather than the shorter `\!`
 * because `\!` is an invalid escape inside a `u`-flag regex literal, and a vendor
 * bundle is minified JavaScript that could contain one. `\u0021` is valid in
 * every context the text can land in: a string, a template literal, and a regex
 * with or without the `u` flag.
 */
export function escapeInlineScript(source: string): string {
  return source
    .replace(/<\/(script)/gi, "<\\/$1")
    .replace(/<!--/g, "<\\u0021--");
}

/**
 * `public/sandbox/sound.js` is an ES module (`export const soundFx`), and the
 * export has to load it as a classic script: an inline `type="module"` is
 * deferred, so it would run after the boot script that needs `window.soundFx`.
 *
 * Only the module boundary is removed, never anything inside a string, so the
 * file keeps its meaning. `import` lines are dropped whole — `sound.js` has none,
 * and a classic script has no way to resolve one anyway.
 */
export function stripModuleSyntax(source: string): string {
  return source
    .replace(/^[ \t]*export[ \t]+(?=(?:const|let|var|function|class)\b)/gm, "")
    .replace(/^[ \t]*export[ \t]+default[ \t]+/gm, "")
    .replace(/^[ \t]*export[ \t]*\{[^}]*\}[ \t]*;?[ \t]*$/gm, "")
    .replace(/^[ \t]*import[ \t][^;]*;?[ \t]*$/gm, "");
}
