/**
 * Escaping and module-syntax helpers shared by the export builders.
 *
 * Both exported artifacts embed generated scene source and baked JSON inside
 * `<script>` elements. The HTML parser ends a script element at the first
 * `</script` sequence wherever it appears — inside a string literal, inside a
 * regex, inside minified vendor code — so a scene that merely mentions it would
 * truncate the file and leave a page that silently does nothing.
 */

/** For text nodes and attribute values, e.g. the `<title>` element. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * For content placed inside a `<script>` element.
 *
 * `<\/script` is the escape the HTML parser expects, and in JavaScript the two
 * spellings are the same string, so the code keeps its meaning. This is applied
 * to the scene source, the baked manifest, and the vendor bundles alike: the
 * source is machine-generated, but "generated by a model" is not a reason to
 * trust that it never contains the sequence.
 */
export function escapeInlineScript(source: string): string {
  return source.replace(/<\/(script)/gi, "<\\/$1");
}

/**
 * `public/sandbox/sound.js` is an ES module (`export const soundFx`), and the
 * export has to load it as a classic script: an inline `type="module"` is
 * deferred, so it would run after the boot script that needs `window.soundFx`.
 *
 * Only the module boundary is removed, never anything inside a string, so the
 * file keeps its meaning. `import` lines are dropped whole — `sound.js` has none,
 * and a classic script has no way to resolve one anyway.
 */
export function stripModuleSyntax(source: string): string {
  return source
    .replace(/^[ \t]*export[ \t]+(?=(?:const|let|var|function|class)\b)/gm, "")
    .replace(/^[ \t]*export[ \t]+default[ \t]+/gm, "")
    .replace(/^[ \t]*export[ \t]*\{[^}]*\}[ \t]*;?[ \t]*$/gm, "")
    .replace(/^[ \t]*import[ \t][^;]*;?[ \t]*$/gm, "");
}
