/**
 * Fetches the vendored runtime the export embeds.
 *
 * These are the same files the sandbox frame loads, served from `/sandbox/` with
 * `Access-Control-Allow-Origin: *`. That header exists for the opaque-origin
 * frame, and it is also what lets the Studio origin read them for an export, so
 * no server-side filesystem read is involved — which matters because
 * `public/sandbox/vendor/` is generated by `postinstall` and is not guaranteed to
 * be readable from a deployed function's working directory.
 */

export interface ExportVendorSources {
  readonly phaser: string;
  readonly riffwave: string;
  readonly sfxr: string;
  readonly sound: string;
}

export const VENDOR_PATHS = {
  riffwave: "/sandbox/vendor/jsfxr/riffwave.js",
  sfxr: "/sandbox/vendor/jsfxr/sfxr.js",
  phaser: "/sandbox/vendor/phaser.min.js",
  sound: "/sandbox/sound.js",
} as const;

const vendorCache: { current: ExportVendorSources | null } = { current: null };

async function fetchText(path: string): Promise<string> {
  const response = await fetch(path);

  if (!response.ok) {
    throw new Error(`Could not load ${path} (HTTP ${response.status}).`);
  }

  return response.text();
}

/**
 * Cached for the life of the page: the vendored files only change on redeploy,
 * and a second export should not re-download a megabyte of Phaser.
 */
export async function fetchVendorSources(): Promise<ExportVendorSources> {
  if (vendorCache.current !== null) {
    return vendorCache.current;
  }

  const [riffwave, sfxr, phaser, sound] = await Promise.all([
    fetchText(VENDOR_PATHS.riffwave),
    fetchText(VENDOR_PATHS.sfxr),
    fetchText(VENDOR_PATHS.phaser),
    fetchText(VENDOR_PATHS.sound),
  ]);

  vendorCache.current = { riffwave, sfxr, phaser, sound };

  return vendorCache.current;
}
